# Generated by Django 4.2.4 on 2023-11-23 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, unique=True)),
                ('extra_content', models.CharField(max_length=4096, unique=True)),
                ('isAvailable', models.CharField(choices=[(1, 'Available'), (0, 'Unavailable')], default=0, max_length=2)),
                ('model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentList',
            fields=[
                ('name', models.CharField(max_length=450, unique=True)),
                ('extra_content', models.CharField(max_length=4096, unique=True)),
                ('isAvailable', models.CharField(choices=[(1, 'Available'), (0, 'Unavailable')], default=0, max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentslist', to='workspace.component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('name', models.CharField(max_length=450, unique=True)),
                ('extra_content', models.CharField(max_length=4096, unique=True)),
                ('isAvailable', models.CharField(choices=[(1, 'Available'), (0, 'Unavailable')], default=0, max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputs', models.CharField(max_length=512)),
                ('outputs', models.CharField(max_length=512)),
                ('boardStatus', models.CharField(choices=[(0, 'BUSY'), (1, 'READY'), (2, 'TESTING')], default=2, max_length=45)),
                ('components', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentslist', to='workspace.componentlist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
