# Generated by Django 4.2.4 on 2023-11-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, unique=True)),
                ('extra_content', models.CharField(max_length=4096, unique=True)),
                ('isAvailable', models.CharField(choices=[(1, 'Available'), (0, 'Unavailable')], default=0, max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='componenttype', to='workspace.componenttype'),
        ),
    ]
