# Generated by Django 4.2.4 on 2023-11-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_component_isavailable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='componentlist',
            name='elements',
        ),
        migrations.AddField(
            model_name='component',
            name='elements',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='componentsinlist', to='workspace.componentlist'),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='component',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='componentsoftype', to='workspace.component'),
        ),
        migrations.AlterField(
            model_name='componentlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
