# Generated by Django 4.2.4 on 2023-11-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_remove_component_component_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainboard',
            name='boardStatus',
            field=models.IntegerField(choices=[(0, 'BUSY'), (1, 'READY'), (2, 'TESTING')], default=2),
        ),
    ]
