# Generated by Django 4.2.4 on 2023-09-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='career',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='users.careers'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAvailable', models.CharField(choices=[(1, 'Available'), (0, 'Unavailable')], default=0, max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.CharField(max_length=45)),
                ('SerializedSet', models.CharField(max_length=4000, null=True)),
                ('subject', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_subject', to='users.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
