# Generated by Django 4.2.4 on 2023-09-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_careers_name_alter_subject_career_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuinoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_1/% Y/% m/% d/')),
            ],
        ),
    ]
