# Generated by Django 4.2.4 on 2023-09-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_duinofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duinofile',
            name='file',
            field=models.FileField(upload_to='user_1/09-27-2023-00:08:27/'),
        ),
    ]
