# Generated by Django 4.2.4 on 2023-09-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_duinofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duinofile',
            name='file',
            field=models.FileField(upload_to='user_1/09-27-2023-01:22:45/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isAvailable',
            field=models.CharField(choices=[(1, 'Available'), (0, 'Unavailable')], default=0, max_length=2),
        ),
    ]
