# Generated by Django 4.2.4 on 2023-11-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_duinofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duinofile',
            name='file',
            field=models.FileField(upload_to='user_1/11-23-2023-08:04:23/'),
        ),
    ]
